/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InnerRouteImport } from './routes/_inner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InnerWorkshopRouteImport } from './routes/_inner.workshop'
import { Route as InnerVenueRouteImport } from './routes/_inner.venue'
import { Route as InnerTracksRouteImport } from './routes/_inner.tracks'
import { Route as InnerSubmissionRouteImport } from './routes/_inner.submission'
import { Route as InnerRegistrationRouteImport } from './routes/_inner.registration'
import { Route as InnerPublicationRouteImport } from './routes/_inner.publication'
import { Route as InnerProgramRouteImport } from './routes/_inner.program'
import { Route as InnerImportantDatesRouteImport } from './routes/_inner.important-dates'
import { Route as InnerContactRouteImport } from './routes/_inner.contact'
import { Route as InnerCommitteeRouteImport } from './routes/_inner.committee'
import { Route as InnerCallForPapersRouteImport } from './routes/_inner.call-for-papers'
import { Route as InnerAuthorGuidelinesRouteImport } from './routes/_inner.author-guidelines'
import { Route as InnerAboutRouteImport } from './routes/_inner.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InnerRoute = InnerRouteImport.update({
  id: '/_inner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InnerWorkshopRoute = InnerWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => InnerRoute,
} as any)
const InnerVenueRoute = InnerVenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => InnerRoute,
} as any)
const InnerTracksRoute = InnerTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => InnerRoute,
} as any)
const InnerSubmissionRoute = InnerSubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => InnerRoute,
} as any)
const InnerRegistrationRoute = InnerRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => InnerRoute,
} as any)
const InnerPublicationRoute = InnerPublicationRouteImport.update({
  id: '/publication',
  path: '/publication',
  getParentRoute: () => InnerRoute,
} as any)
const InnerProgramRoute = InnerProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => InnerRoute,
} as any)
const InnerImportantDatesRoute = InnerImportantDatesRouteImport.update({
  id: '/important-dates',
  path: '/important-dates',
  getParentRoute: () => InnerRoute,
} as any)
const InnerContactRoute = InnerContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => InnerRoute,
} as any)
const InnerCommitteeRoute = InnerCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => InnerRoute,
} as any)
const InnerCallForPapersRoute = InnerCallForPapersRouteImport.update({
  id: '/call-for-papers',
  path: '/call-for-papers',
  getParentRoute: () => InnerRoute,
} as any)
const InnerAuthorGuidelinesRoute = InnerAuthorGuidelinesRouteImport.update({
  id: '/author-guidelines',
  path: '/author-guidelines',
  getParentRoute: () => InnerRoute,
} as any)
const InnerAboutRoute = InnerAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => InnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof InnerAboutRoute
  '/author-guidelines': typeof InnerAuthorGuidelinesRoute
  '/call-for-papers': typeof InnerCallForPapersRoute
  '/committee': typeof InnerCommitteeRoute
  '/contact': typeof InnerContactRoute
  '/important-dates': typeof InnerImportantDatesRoute
  '/program': typeof InnerProgramRoute
  '/publication': typeof InnerPublicationRoute
  '/registration': typeof InnerRegistrationRoute
  '/submission': typeof InnerSubmissionRoute
  '/tracks': typeof InnerTracksRoute
  '/venue': typeof InnerVenueRoute
  '/workshop': typeof InnerWorkshopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof InnerAboutRoute
  '/author-guidelines': typeof InnerAuthorGuidelinesRoute
  '/call-for-papers': typeof InnerCallForPapersRoute
  '/committee': typeof InnerCommitteeRoute
  '/contact': typeof InnerContactRoute
  '/important-dates': typeof InnerImportantDatesRoute
  '/program': typeof InnerProgramRoute
  '/publication': typeof InnerPublicationRoute
  '/registration': typeof InnerRegistrationRoute
  '/submission': typeof InnerSubmissionRoute
  '/tracks': typeof InnerTracksRoute
  '/venue': typeof InnerVenueRoute
  '/workshop': typeof InnerWorkshopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_inner': typeof InnerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_inner/about': typeof InnerAboutRoute
  '/_inner/author-guidelines': typeof InnerAuthorGuidelinesRoute
  '/_inner/call-for-papers': typeof InnerCallForPapersRoute
  '/_inner/committee': typeof InnerCommitteeRoute
  '/_inner/contact': typeof InnerContactRoute
  '/_inner/important-dates': typeof InnerImportantDatesRoute
  '/_inner/program': typeof InnerProgramRoute
  '/_inner/publication': typeof InnerPublicationRoute
  '/_inner/registration': typeof InnerRegistrationRoute
  '/_inner/submission': typeof InnerSubmissionRoute
  '/_inner/tracks': typeof InnerTracksRoute
  '/_inner/venue': typeof InnerVenueRoute
  '/_inner/workshop': typeof InnerWorkshopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/about'
    | '/author-guidelines'
    | '/call-for-papers'
    | '/committee'
    | '/contact'
    | '/important-dates'
    | '/program'
    | '/publication'
    | '/registration'
    | '/submission'
    | '/tracks'
    | '/venue'
    | '/workshop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/about'
    | '/author-guidelines'
    | '/call-for-papers'
    | '/committee'
    | '/contact'
    | '/important-dates'
    | '/program'
    | '/publication'
    | '/registration'
    | '/submission'
    | '/tracks'
    | '/venue'
    | '/workshop'
  id:
    | '__root__'
    | '/'
    | '/_inner'
    | '/sitemap.xml'
    | '/_inner/about'
    | '/_inner/author-guidelines'
    | '/_inner/call-for-papers'
    | '/_inner/committee'
    | '/_inner/contact'
    | '/_inner/important-dates'
    | '/_inner/program'
    | '/_inner/publication'
    | '/_inner/registration'
    | '/_inner/submission'
    | '/_inner/tracks'
    | '/_inner/venue'
    | '/_inner/workshop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InnerRoute: typeof InnerRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_inner': {
      id: '/_inner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_inner/workshop': {
      id: '/_inner/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof InnerWorkshopRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/venue': {
      id: '/_inner/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof InnerVenueRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/tracks': {
      id: '/_inner/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof InnerTracksRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/submission': {
      id: '/_inner/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof InnerSubmissionRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/registration': {
      id: '/_inner/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof InnerRegistrationRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/publication': {
      id: '/_inner/publication'
      path: '/publication'
      fullPath: '/publication'
      preLoaderRoute: typeof InnerPublicationRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/program': {
      id: '/_inner/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof InnerProgramRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/important-dates': {
      id: '/_inner/important-dates'
      path: '/important-dates'
      fullPath: '/important-dates'
      preLoaderRoute: typeof InnerImportantDatesRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/contact': {
      id: '/_inner/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof InnerContactRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/committee': {
      id: '/_inner/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof InnerCommitteeRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/call-for-papers': {
      id: '/_inner/call-for-papers'
      path: '/call-for-papers'
      fullPath: '/call-for-papers'
      preLoaderRoute: typeof InnerCallForPapersRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/author-guidelines': {
      id: '/_inner/author-guidelines'
      path: '/author-guidelines'
      fullPath: '/author-guidelines'
      preLoaderRoute: typeof InnerAuthorGuidelinesRouteImport
      parentRoute: typeof InnerRoute
    }
    '/_inner/about': {
      id: '/_inner/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof InnerAboutRouteImport
      parentRoute: typeof InnerRoute
    }
  }
}

interface InnerRouteChildren {
  InnerAboutRoute: typeof InnerAboutRoute
  InnerAuthorGuidelinesRoute: typeof InnerAuthorGuidelinesRoute
  InnerCallForPapersRoute: typeof InnerCallForPapersRoute
  InnerCommitteeRoute: typeof InnerCommitteeRoute
  InnerContactRoute: typeof InnerContactRoute
  InnerImportantDatesRoute: typeof InnerImportantDatesRoute
  InnerProgramRoute: typeof InnerProgramRoute
  InnerPublicationRoute: typeof InnerPublicationRoute
  InnerRegistrationRoute: typeof InnerRegistrationRoute
  InnerSubmissionRoute: typeof InnerSubmissionRoute
  InnerTracksRoute: typeof InnerTracksRoute
  InnerVenueRoute: typeof InnerVenueRoute
  InnerWorkshopRoute: typeof InnerWorkshopRoute
}

const InnerRouteChildren: InnerRouteChildren = {
  InnerAboutRoute: InnerAboutRoute,
  InnerAuthorGuidelinesRoute: InnerAuthorGuidelinesRoute,
  InnerCallForPapersRoute: InnerCallForPapersRoute,
  InnerCommitteeRoute: InnerCommitteeRoute,
  InnerContactRoute: InnerContactRoute,
  InnerImportantDatesRoute: InnerImportantDatesRoute,
  InnerProgramRoute: InnerProgramRoute,
  InnerPublicationRoute: InnerPublicationRoute,
  InnerRegistrationRoute: InnerRegistrationRoute,
  InnerSubmissionRoute: InnerSubmissionRoute,
  InnerTracksRoute: InnerTracksRoute,
  InnerVenueRoute: InnerVenueRoute,
  InnerWorkshopRoute: InnerWorkshopRoute,
}

const InnerRouteWithChildren = InnerRoute._addFileChildren(InnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InnerRoute: InnerRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
